<?php get_header(); /* Template Name: Home page */ ?> 
<style type="text/css"> .clearfix{ clear: both; } .tvshowclass .tvshowsimageclass{ min-height: 170px; } .only-mobile{ display: none; } @media (max-width: 500px){ .only-mobile{ display: block; } } </style>
<ul class="slider"><?php query_posts('cat=87'); if(have_posts()): while ( have_posts() ) : the_post(); ?><li class="slide"><?php  $feat_image = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID) ,'full');?><?php if( $feat_image): ?><img src='<?php echo $feat_image[0]; ?>' title='<?php echo get_the_title(); ?>' alt='<?php echo get_the_title(); ?>'><?php endif; ?><div class="slider_content_box"><ul class="post_details simple"><a href="<?php echo get_permalink(); ?>"><li class="category"><?php $posttags = get_the_tags();?><?php  if ($posttags) { $tagcount12=1; foreach($posttags as $tag) { if($tagcount12==1){ ?> <a href="<?php echo get_tag_link($tag->term_id); ?>" title='<?php echo get_the_title(); ?>'> <?php echo $tag->name; ?> </a><?php } $tagcount12++; } } ?> </li> </a> <li class="date"> <?php echo get_the_date('g:i A, F j' ); ?> </li> </ul> <h2><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php echo substr(get_the_title(),0,75); ?></a></h2><p class="clearfix"><?php echo substr(get_the_excerpt(),0,150); ?>...</p></div></li><?php endwhile; endif; ?></ul>
<?php 
	function get_number_videos($number){
		$conn22 = new PDO("mysql:host=localhost;dbname=srikanth_livecricketinfo","kallemvideos",'K@sreekanth8' );
		$sql = "SELECT * FROM videos ORDER BY ID DESC LIMIT 4";
		$res = $conn22->prepare($sql);
		$res->execute();
		$data = new ArrayObject();
		while($row = $res->fetch()) {
			$data[] = $row;
	  	}
		return $data;
	}
?>
<div class="page">
<div class='slider_posts_list_container'></div>
<div class="page_layout page_margin_top clearfix"><div class="row"><div class="column"><h4 class="box_header">Popular Shows <a class="more homepagemore page_margin_top" href="http://www.livevideoshub.com/category/video-songs/">MORE </a></h4><div class="row"><ul class="tvshowclass homepage"><?php query_posts('cat=87&posts_per_page=4'); if(have_posts()): $count=1; while ( have_posts() ) : the_post(); ?><li><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php  $feat_image = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID),'medium' );?><?php if( $feat_image): ?><img src='<?php echo $feat_image[0]; ?>' title='<?php echo get_the_title(); ?>' alt='<?php echo get_the_title(); ?>'><?php endif; ?><span class="post-image-play-button" ></span><?php if(get_field('video_length')): ?><span class="timier" ><?php echo get_field('video_length'); ?></span><?php endif; ?></a><div class="post-title"><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php echo get_the_title(); ?></a><div class="post-date"><span></span><?php echo get_the_date(); ?></div></div></li><?php if($count==1||$count==3): ?><li class="only-mobile"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-1518250080154239" data-ad-slot="2550265139" data-ad-format="auto"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></li><?php endif; ?><?php if($count==2): ?><li class="only-mobile"><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Sidebar -->
<ins class="adsbygoogle"
     style="display:inline-block;width:336px;height:280px"
     data-ad-client="ca-pub-1518250080154239"
     data-ad-slot="7259666331"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></li><?php endif; $count++; endwhile; endif; ?></ul></div>
<div class="row "><h4 class="box_header">Telugu Video Songs <a class="more homepagemore page_margin_top" href="http://www.livevideoshub.com/category/video-songs/">MORE </a></h4><ul class="tvshowclass homepage"><?php query_posts('cat=5&posts_per_page=4'); if(have_posts()): $count=1; while ( have_posts() ) : the_post(); ?><li><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php  $feat_image = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID),'medium' );?><?php if( $feat_image): ?><img src='<?php echo $feat_image[0]; ?>' title='<?php echo get_the_title(); ?>' alt='<?php echo get_the_title(); ?>'><?php endif; ?><span class="post-image-play-button" ></span><?php if(get_field('video_length')): ?><span class="timier" ><?php echo get_field('video_length'); ?></span><?php endif; ?></a><div class="post-title"><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php echo get_the_title(); ?></a><div class="post-date"><span></span><?php echo get_the_date(); ?></div></div></li><?php endwhile; endif; ?></ul></div>
<div class="row "><h4 class="box_header">Latest Telugu Movies <a class="more homepagemore page_margin_top" href="http://www.livevideoshub.com/category/telugu-movies/">MORE </a></h4><ul class="tvshowclass homepage"><?php query_posts('cat=322&posts_per_page=4'); if(have_posts()): $count=1; while ( have_posts() ) : the_post(); ?><li><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php  $feat_image = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID),'medium' );?><?php if( $feat_image): ?><img src='<?php echo $feat_image[0]; ?>' title='<?php echo get_the_title(); ?>' alt='<?php echo get_the_title(); ?>'><?php endif; ?><span class="post-image-play-button" ></span><?php if(get_field('video_length')): ?><span class="timier" ><?php echo get_field('video_length'); ?></span><?php endif; ?></a><div class="post-title"><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php echo get_the_title(); ?></a><div class="post-date"><span></span><?php echo get_the_date(); ?></div></div></li><?php endwhile; endif; ?></ul></div>

<div class="row "><h4 class="box_header">Hindi Video Songs <a class="more homepagemore page_margin_top" href="http://www.livevideoshub.com/category/hindi-video-songs/">MORE </a></h4><ul class="tvshowclass homepage"><?php query_posts('cat=160&posts_per_page=4'); if(have_posts()): $count=1; while ( have_posts() ) : the_post(); ?><li><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php  $feat_image = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID),'medium' );?><?php if( $feat_image): ?><img src='<?php echo $feat_image[0]; ?>' title='<?php echo get_the_title(); ?>' alt='<?php echo get_the_title(); ?>'><?php endif; ?><span class="post-image-play-button" ></span><?php if(get_field('video_length')): ?><span class="timier" ><?php echo get_field('video_length'); ?></span><?php endif; ?></a><div class="post-title"><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php echo get_the_title(); ?></a><div class="post-date"><span></span><?php echo get_the_date(); ?></div></div></li><?php endwhile; endif; ?></ul></div>

<div class="row "><h4 class="box_header">Punjabi Video Songs <a class="more homepagemore page_margin_top" href="http://www.livevideoshub.com/category/punjabi/">MORE </a></h4><ul class="tvshowclass homepage"><?php query_posts('cat=389&posts_per_page=4'); if(have_posts()): $count=1; while ( have_posts() ) : the_post(); ?><li><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php  $feat_image = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID),'medium' );?><?php if( $feat_image): ?><img src='<?php echo $feat_image[0]; ?>' title='<?php echo get_the_title(); ?>' alt='<?php echo get_the_title(); ?>'><?php endif; ?><span class="post-image-play-button" ></span><?php if(get_field('video_length')): ?><span class="timier" ><?php echo get_field('video_length'); ?></span><?php endif; ?></a><div class="post-title"><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php echo get_the_title(); ?></a><div class="post-date"><span></span><?php echo get_the_date(); ?></div></div></li><?php endwhile; endif; ?></ul></div>

<div class="row"><h4 class="box_header">Hindi Movie Trailers <a class="more homepagemore page_margin_top" href="http://www.livevideoshub.com/category/hindi-trailers/">MORE </a></h4><ul class="tvshowclass homepage"><?php query_posts('cat=148&posts_per_page=4'); if(have_posts()): $count=1; while ( have_posts() ) : the_post(); ?><li><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php  $feat_image = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID),'medium' );?><?php if( $feat_image): ?><img src='<?php echo $feat_image[0]; ?>' title='<?php echo get_the_title(); ?>' alt='<?php echo get_the_title(); ?>'><?php endif; ?><span class="post-image-play-button" ></span><?php if(get_field('video_length')): ?><span class="timier" ><?php echo get_field('video_length'); ?></span><?php endif; ?></a><div class="post-title"><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php echo get_the_title(); ?></a><div class="post-date"><span></span><?php echo get_the_date(); ?></div></div></li><?php endwhile; endif; ?> </ul></div>
<div class="row"><h4 class="box_header">Telugu Movie Trailers <a class="more homepagemore page_margin_top" href="http://www.livevideoshub.com/category/trailers/">MORE </a></h4><ul class="tvshowclass homepage"><?php query_posts('cat=4&posts_per_page=4'); if(have_posts()): $count=1; while ( have_posts() ) : the_post(); ?><li><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php  $feat_image = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID),'medium' );?><?php if( $feat_image): ?><img src='<?php echo $feat_image[0]; ?>' title='<?php echo get_the_title(); ?>' alt='<?php echo get_the_title(); ?>'><?php endif; ?><span class="post-image-play-button" ></span><?php if(get_field('video_length')): ?><span class="timier" ><?php echo get_field('video_length'); ?></span><?php endif; ?></a><div class="post-title"><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php echo get_the_title(); ?></a><div class="post-date"><span></span><?php echo get_the_date(); ?></div></div></li><?php endwhile; endif; ?></ul></div>
<div class="row"><h4 class="box_header">Comedy Videos <a class="more homepagemore page_margin_top" href="http://www.livevideoshub.com/category/comedy/">MORE </a></h4><ul class="tvshowclass homepage"><?php query_posts('cat=70&posts_per_page=8'); if(have_posts()): $count=1; while ( have_posts() ) : the_post(); ?><li><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php  $feat_image = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID),'medium' );?><?php if( $feat_image): ?><img src='<?php echo $feat_image[0]; ?>' title='<?php echo get_the_title(); ?>' alt='<?php echo get_the_title(); ?>'><?php endif; ?><span class="post-image-play-button" ></span><?php if(get_field('video_length')): ?><span class="timier" ><?php echo get_field('video_length'); ?></span><?php endif; ?></a><div class="post-title"><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php echo get_the_title(); ?></a><div class="post-date"><span></span><?php echo get_the_date(); ?></div></div></li><?php endwhile; endif; ?></ul></div>
<div class="row"><h4 class="box_header">TV Shows <a class="more homepagemore page_margin_top" href="https://www.livevideoshub.com/tv-shows/">MORE </a></h4><ul class="tvshowclass"><li><a href="https://www.livevideoshub.com/category/the-kapil-sharma-show" title="The Kapil Sharma Show"><img src="https://www.livevideoshub.com/wp-content/uploads/2016/08/The-Kapil-Sharma-Show-21st-August-2016-Full-Episode.jpg" title="" alt="The Kapil Sharma Show" class="tvshowsimageclass"></a><h5><a href="https://www.livevideoshub.com/category/the-kapil-sharma-show" title="The Kapil Sharma Show">The Kapil Sharma Show</a></h5></li><li><a href="https://www.livevideoshub.com/category/comedy-nights-bachao" title="Comedy Nights Bachao"><img src="https://www.livevideoshub.com/wp-content/uploads/2016/08/Comedy-Nights-Bachao.jpg" class="tvshowsimageclass" title="" alt="Comedy Nights Bachao"></a><h5><a href="https://www.livevideoshub.com/category/comedy-nights-bachao" title="Comedy Nights Bachao">Comedy Nights Bachao</a></h5></li><li><a href="https://www.livevideoshub.com/category/jabardasth" title="Jabardasth"><img src="https://www.livevideoshub.com/wp-content/uploads/2016/08/Jabardasth.jpg" class="tvshowsimageclass" title="" alt="Jabardasth"></a><h5><a href="https://www.livevideoshub.com/category/jabardasth" title="Jabardasth">Jabardasth</a></h5></li><li><a href="https://www.livevideoshub.com/category/dhee-jodi" title="Dhee Jodi"><img src="https://www.livevideoshub.com/wp-content/uploads/2016/08/Dhee-Jodi.jpg" class="tvshowsimageclass" title="" alt="Dhee Jodi"></a><h5><a href="https://www.livevideoshub.com/category/dhee-jodi" title="Dhee Jodi">Dhee Jodi</a></h5></li></ul></div>
<?php 
	$cricketvideos = get_number_videos(4);

?>
<div class="row"><h4 class="box_header">Latest Cricket Videos<a class="more homepagemore page_margin_top" href="http://www.livecricketinfo.com/videos">MORE </a></h4><ul class="tvshowclass homepage"><?php foreach($cricketvideos as $video): ?><li><a href="http://www.livecricketinfo.com/cricket-videos/<?php echo $video['url']; ?>/<?php echo $video['ID']; ?>" title="<?php echo $video['videotitle'] ?>"><?php if( $video['videoimage']): ?><img src='http://www.livecricketinfo.com/<?php echo $video['videoimage']; ?>' title='<?php echo $video['videotitle'] ?>' alt='<?php echo $video['videotitle'] ?>'><?php endif; ?><span class="post-image-play-button" ></span></a><div class="post-title"><a href="http://www.livecricketinfo.com/cricket-videos/<?php echo $video['url']; ?>/<?php echo $video['ID']; ?>" title="<?php echo $video['videotitle'] ?>"><?php echo $video['videotitle'] ?></a><div class="post-date"><span></span><?php $dateds =  date_create($video['postdate']); echo date_format($dateds, "F d, Y"); ?></div></div></li><?php endforeach; ?></ul> </div>
<div class="row"><h4 class="box_header">Latest Short Films <a class="more homepagemore page_margin_top" href="http://www.livevideoshub.com/category/short-films/">MORE </a></h4><ul class="tvshowclass homepage"><?php query_posts('cat=9&posts_per_page=4'); if(have_posts()): $count=1; while ( have_posts() ) : the_post(); ?><li><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php  $feat_image = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID),'medium' );?><?php if( $feat_image): ?><img src='<?php echo $feat_image[0]; ?>' title='<?php echo get_the_title(); ?>' alt='<?php echo get_the_title(); ?>'><?php endif; ?><span class="post-image-play-button" ></span><?php if(get_field('video_length')): ?><span class="timier" ><?php echo get_field('video_length'); ?></span><?php endif; ?></a><div class="post-title"><a href="<?php echo get_permalink(); ?>" title="<?php echo get_the_title(); ?>"><?php echo get_the_title(); ?></a><div class="post-date"><span></span><?php echo get_the_date(); ?></div></div></li><?php endwhile; endif; ?></ul> </div></div></div></div></div><?php get_footer(); ?>